# Generated by Django 2.2 on 2019-08-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0002_auto_20190829_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='topic',
            name='end_date',
            field=models.DateTimeField(),
        ),
    ]
