# Generated by Django 2.2 on 2019-08-24 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0003_auto_20190820_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicvideo',
            name='course',
        ),
    ]
