# Generated by Django 2.0.1 on 2019-09-13 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20190901_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='category.Category'),
        ),
        migrations.AlterField(
            model_name='discountcoupon',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discountchild', to='course.Course'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topicchild', to='course.Course'),
        ),
        migrations.AlterModelTable(
            name='course',
            table='course',
        ),
    ]
