# Generated by Django 2.2 on 2019-08-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0005_auto_20190829_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
