# Generated by Django 2.2 on 2019-09-01 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='meta_descrition',
            new_name='meta_description',
        ),
    ]
