# Generated by Django 2.2.4 on 2019-09-02 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table='course',
        ),
    ]
