# Generated by Django 2.2 on 2019-08-15 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CategoryApp', '0003_auto_20190815_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('faculty_name', models.CharField(max_length=50)),
                ('course_image', models.ImageField(upload_to='uploads/')),
                ('no_of_class', models.IntegerField(blank=True, null=True, verbose_name='Number of Videos')),
                ('course_detail', models.TextField()),
                ('course_type', models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid')], default='Free', max_length=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='CategoryApp.Category')),
            ],
        ),
    ]
