# Generated by Django 2.2 on 2019-08-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_title',
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default=3, max_length=120, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='course_detail',
            field=models.TextField(verbose_name='Detail'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
