# Generated by Django 2.2 on 2019-08-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoryApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(default='Active', max_length=10),
            preserve_default=False,
        ),
    ]
