# Generated by Django 2.2 on 2019-08-08 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoryApp', '0003_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('a', 'Active'), ('i', 'Inactive')], max_length=10),
        ),
    ]
